python vanilla_0.01.py -i method_comparison/2REB.pdb
python vanilla_0.1.py -i method_comparison/2REB.pdb
python vanilla_1.py -i method_comparison/2REB.pdb
python vanilla_10.py -i method_comparison/2REB.pdb
python vanilla_50.py -i method_comparison/2REB.pdb
python bfgs_0.01.py -i method_comparison/2REB.pdb
python bfgs_0.1.py -i method_comparison/2REB.pdb
python bfgs_1.py -i method_comparison/2REB.pdb
python bfgs_10.py -i method_comparison/2REB.pdb
python bfgs_50.py -i method_comparison/2REB.pdb
python conjugate_gradient_0.01.py -i method_comparison/2REB.pdb
python conjugate_gradient_0.1.py -i method_comparison/2REB.pdb
python conjugate_gradient_1.py -i method_comparison/2REB.pdb
python conjugate_gradient_10.py -i method_comparison/2REB.pdb
python conjugate_gradient_50.py -i method_comparison/2REB.pdb
